### ISSUE TITLE
Strange country detection case

### ISSUE THREAD

**Issue by sejoker** [willscott/ip2country#6]
Hi
I tested your package with such ip: '159.122.94.105'
it detects US, although both websites detect Germany, Frankfurt.
http://www.infosniper.net/index.php
https://www.iplocation.net/
Could you elaborate on this case?

**Comment by willscott** [comment]
Interesting!

whois seems to indicate the correct location would be CZ
inetnum:        159.122.94.96 - 159.122.94.111
netname:        NETBLK-SOFTLAYER-RIPE-CUST-RO3013-RIPE
descr:          Testomato
country:        CZ
admin-c:        RO3013-RIPE
tech-c:         RO3013-RIPE


We do say US, because the origin AS says that the
159.122.94.* space is owned by AS 36351, which is IBM SoftLayer.
http://www.tcpiputils.com/browse/ip-address/159.122.94.104

To get finer grained than just the owning organization, we'll need to
decide if we want to trust the WHOIS data that they self-report, or do
latency measurements to learn that for ourselves.

**Comment by sejoker** [comment]
thanks for clarification.

**Comment by tomac4t** [comment]
Interesting case, traceroute and rDNS show that "159.122.94.105" near Frankfurt, Germany:
```bash
$ sudo traceroute 159.122.94.105 -I
traceroute to 159.122.94.105 (159.122.94.105), 30 hops max, 60 byte packets
[...]
 5  te1-7.bbr01.tl01.nyc01.networklayer.com (198.32.160.27)  1.355 ms  1.366 ms  1.421 ms
 6  ae5.cbs02.tl01.nyc01.networklayer.com (50.97.17.42)  2.192 ms  1.879 ms *
 7  ae1.cbs01.tg01.lon01.networklayer.com (169.45.19.47)  70.021 ms * *
 8  ae0.cbs01.xn01.fra01.networklayer.com (50.97.19.190)  84.208 ms  84.487 ms  84.498 ms
 9  f9.13.2da9.ip4.static.sl-reverse.com (169.45.19.249)  85.098 ms  85.177 ms  84.891 ms
10  87.76.b19e.ip4.static.sl-reverse.com (158.177.118.135)  85.787 ms  85.755 ms  85.770 ms
11  69.5e.7a9f.ip4.static.sl-reverse.com (159.122.94.105)  84.127 ms  83.845 ms  84.080 ms
```

That's probably the reason why IP2Location said it's in German.
